# See: https://dart.dev/tools/pub/pubspec
---
name: know
version: 0.0.1
description: The Know Framework for Dart
homepage: https://know.dev
repository: https://github.com/HaltiaAI/know.dart
issue_tracker: https://github.com/HaltiaAI/know.dart/issues
documentation: https://github.com/HaltiaAI/know.dart/blob/master/README.md
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  meta: ^1.11.0
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
